name: Deploy to Instances

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker
        run: docker login  -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Call Discord webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Server deployment `${{ github.sha }}` is currently being rolled out.'

      - name: Build server image
        run: docker build . --tag skyefoxie/trident-tf2:${{ github.sha }}

      - name: Push image to Docker Hub
        run: docker push skyefoxie/trident-tf2

